name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          use-cache: false

      - name: Run `run` step
        run: zig build run

  test:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          use-cache: false

      - name: Run `test` step
        run: zig build test --summary all

  fmt:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up Zig
        uses: https://github.com/mlugg/setup-zig@v2
        with:
          use-cache: false

      - name: Run `fmt` step
        run: zig build fmt$s$l
