name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  run:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Set up Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Run `run` step
        run: zig build run

  test:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Set up Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Run `test` step
        run: zig build test --summary all

  fmt:
    runs-on: codeberg-tiny-lazy

    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v6

      - name: Set up Zig
        uses: https://codeberg.org/mlugg/setup-zig@v2

      - name: Run `fmt` step
        run: zig build fmt$s$l
